### ISSUE TITLE
How to run Reggie! Dumper on Linux xD

### ISSUE THREAD

**Issue by ZGStuff** [RoadrunnerWMC/Reggie-Updated#22]

**Comment by RoadrunnerWMC** [comment]
It runs on your Wii, not your PC, so your OS doesn't make a difference.

At any rate, Reggie! Dumper is a separate application from the Reggie! Level Editor, so this isn't the right place to talk about it. I suggest joining one of the NSMBW modding Discord servers if you need more help with it, such as [this one](https://discord.gg/nXgyHrMyjA).

**Comment by ZGStuff** [comment]
ah...
i wondered why it was a .DOL and not a normal executable.
