### ISSUE TITLE
build_windows.py doesn't work on python 3

### ISSUE THREAD

**Issue by puyoxyz** [RoadrunnerWMC/Reggie-Updated#3]
ImportError: No module named 'sip'
I installed both PyQt5 and sip, I'm on python 3.8
(i did `python -m pip install PyQt5` then `python -m pip install sip` when it didn't work.)
(i assume this is python3-specific because you added python 3 support after last updating build_windows.py)

i'm trying to build it

**Comment by RoadrunnerWMC** [comment]
PR #1 (merged today) completely replaced the build system, and pre-built binaries are now available on the Releases page (https://github.com/RoadrunnerWMC/Reggie-Updated/releases). In addition, if all you want is to just run Reggie, you should run `reggie.py`, not `build_windows.py` (this is a common mistake).

Anyway, `build_windows.py` doesn't exist anymore, and the new release builds are probably sufficient for most users, so I'll close this issue. If you're still having issues, feel free to comment again or open a new issue. Thanks!
